### ISSUE TITLE
README.md example not working?

### ISSUE THREAD

**Issue by brainstorm** [haadcode/orbit-db#106]
```
$ node orbit_test.js
/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:15
      this._ipfs.pubsub.sub(hash, { discover: true }, (err, stream) => {
                       ^

TypeError: Cannot read property 'sub' of undefined
    at IPFSPubsub.subscribe (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:15:24)
    at OrbitDB._subscribe (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/OrbitDB.js:66:20)
    at OrbitDB._createStore (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/OrbitDB.js:57:17)
    at OrbitDB.eventlog (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/OrbitDB.js:29:17)
    at Object.<anonymous> (/Users/romanvg/dev/cgt-vcfsearch/orbit_test.js:18:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

The other console-based examples under `orbit-db/examples` seem to work, except the browser demo for which I'm getting connection refused to IPFS even when other demos do succeed connecting to it.

**Comment by haadcode** [comment]
Thank @brainstorm for reporting this! What the error indicates is that there's a version mismatch with the js-ipfs-api version (and the one being used doesn't included pubsub). Was this directly after cloning and running npm install? If so, can you try running `npm run postinstall` and see if it works fro you?

**Comment by haadcode** [comment]
Ah, now I understand, you were using orbit-db as a module. Ok, in that case, it almost certainly means that there's another ipfs-api package somewhere that gets picked up (instead the one that orbit-db-pubsub uses). @brainstorm what you can do is run `npm ls ipfs-api` and see where the other version come from. I haven't found a better solution yet that to just delete all the other versions. This is not intended to be final and in future there's going to be only one version.

Does that make sense?

**Comment by brainstorm** [comment]
Thanks @haadcode for the feedback! I recall following the instructions as shown in `README.md`:

```
npm install orbit-db ipfs-api
```

So yes, it seems that `ipfs-api` is being picked up from inside `orbit-db-pubsub` instead?

```
mba:cgt-vcfsearch romanvg$ npm ls ipfs-api
cgt-vcfsearch@1.0.0 /Users/romanvg/dev/cgt-vcfsearch
├── ipfs-api@9.0.0
└─┬ orbit-db@0.12.4
  └─┬ orbit-db-pubsub@0.0.4
    └── ipfs-api@8.1.0  (git+https://github.com/haadcode/js-ipfs-api.git#7e7f6eac63d037870096994a414b259a1ce2061a)
```

**Comment by haadcode** [comment]
@brainstorm ok, I get it. Sorry about that, this is definitely a bug. I fixed and if you re-install orbit-db (version 0.13.1).

```
npm install orbit-db ipfs-api
```

Should work now as stated in the readme.

Thank you for reporting this @brainstorm! ❤️

**Comment by brainstorm** [comment]
Thanks to you @haadcode!

I just `rm -rf node_modules` && `npm install` [my project](https://github.com/brainstorm/cgt-orbitsearch) and it got a bit scarier:

```
mba:cgt-vcfsearch romanvg$ node orbit_t.js
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/romanvg/dev/cgt-vcfsearch/keys/private.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/Keystore.js:10:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/Aggregator.js:9:21)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

Why is it trying to open `keys/private.pem` now? :_(

Below I'm pasting the whole `npm install` log after removing the modules:

```
mba:cgt-vcfsearch romanvg$ npm install
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:78016) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> fibers@1.0.15 install /Users/romanvg/dev/cgt-vcfsearch/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-48` exists; testing
Binary is fine; exiting

> sqlite3@3.1.6 install /Users/romanvg/dev/cgt-vcfsearch/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/romanvg/dev/cgt-vcfsearch/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node" is installed via remote

> go-ipfs-dep@0.4.4-floodsub2 install /Users/romanvg/dev/cgt-vcfsearch/node_modules/go-ipfs-dep
> node src/bin.js $TARGET_OS

Downloading ipfs_floodsub-2_darwin-amd64.tar.gz

> go-ipfs@0.3.10 install /Users/romanvg/dev/cgt-vcfsearch/node_modules/go-ipfs
> node install.js

Downloading ipfs_v0.3.10_darwin-amd64.zip
[============================================>] 100.0% of 6.43 MB (1.29 MB/s)

> ipfs-daemon@0.0.2 postinstall /Users/romanvg/dev/cgt-vcfsearch/node_modules/ipfs-daemon
> ./scripts/post_install.sh

cgt-vcfsearch@1.0.0 /Users/romanvg/dev/cgt-vcfsearch
├─┬ bionode-vcf@1.1.4
│ ├── events@1.1.1
│ ├── fs@0.0.2
│ ├── readline@1.3.0
│ └─┬ stream@0.0.2
│   └── emitter-component@1.1.1
├─┬ ipfs-api@9.0.0
│ ├─┬ async@2.0.1
│ │ └── lodash@4.16.4
│ ├─┬ babel-runtime@6.11.6
│ │ ├── core-js@2.4.1
│ │ └── regenerator-runtime@0.9.5
│ ├─┬ bl@1.1.2
│ │ └─┬ readable-stream@2.0.6
│ │   ├── core-util-is@1.0.2
│ │   ├── isarray@1.0.0
│ │   ├── process-nextick-args@1.0.7
│ │   ├── string_decoder@0.10.31
│ │   └── util-deprecate@1.0.2
│ ├─┬ bs58@3.0.0
│ │ └── base-x@1.0.4
│ ├── detect-node@2.0.3
│ ├── flatmap@0.0.3
│ ├─┬ glob@7.1.1
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.5
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├─┬ minimatch@3.0.3
│ │ │ └─┬ brace-expansion@1.1.6
│ │ │   ├── balanced-match@0.4.2
│ │ │   └── concat-map@0.0.1
│ │ ├── once@1.4.0
│ │ └── path-is-absolute@1.0.1
│ ├─┬ ipfs-block@0.3.0
│ │ └─┬ multihashing@0.2.1
│ │   └─┬ webcrypto@0.1.0
│ │     └─┬ crypto-browserify@3.11.0
│ │       ├─┬ browserify-cipher@1.0.0
│ │       │ ├─┬ browserify-aes@1.0.6
│ │       │ │ └── buffer-xor@1.0.3
│ │       │ ├─┬ browserify-des@1.0.0
│ │       │ │ └─┬ des.js@1.0.0
│ │       │ │   └── minimalistic-assert@1.0.0
│ │       │ └── evp_bytestokey@1.0.0
│ │       ├─┬ browserify-sign@4.0.0
│ │       │ ├── browserify-rsa@4.0.1
│ │       │ └─┬ parse-asn1@5.0.0
│ │       │   └── asn1.js@4.8.1
│ │       ├── create-ecdh@4.0.0
│ │       ├─┬ create-hash@1.1.2
│ │       │ ├── cipher-base@1.0.3
│ │       │ ├── ripemd160@1.0.1
│ │       │ └── sha.js@2.4.5
│ │       ├── create-hmac@1.1.4
│ │       ├─┬ diffie-hellman@5.0.2
│ │       │ └── miller-rabin@4.0.0
│ │       ├── pbkdf2@3.0.9
│ │       ├── public-encrypt@4.0.0
│ │       └── randombytes@2.0.3
│ ├─┬ ipfs-merkle-dag@0.7.3
│ │ ├── multihashes@0.2.2
│ │ ├─┬ protocol-buffers@3.1.6
│ │ │ ├─┬ brfs@1.4.3
│ │ │ │ ├─┬ quote-stream@1.0.2
│ │ │ │ │ └── buffer-equal@0.0.1
│ │ │ │ ├── resolve@1.1.7
│ │ │ │ ├─┬ static-module@1.3.1
│ │ │ │ │ ├─┬ concat-stream@1.4.10
│ │ │ │ │ │ └─┬ readable-stream@1.1.14
│ │ │ │ │ │   └── isarray@0.0.1
│ │ │ │ │ ├─┬ duplexer2@0.0.2
│ │ │ │ │ │ └─┬ readable-stream@1.1.14
│ │ │ │ │ │   └── isarray@0.0.1
│ │ │ │ │ ├─┬ escodegen@1.3.3
│ │ │ │ │ │ ├── esprima@1.1.1
│ │ │ │ │ │ ├── estraverse@1.5.1
│ │ │ │ │ │ └── esutils@1.0.0
│ │ │ │ │ ├─┬ falafel@1.2.0
│ │ │ │ │ │ ├── acorn@1.2.2
│ │ │ │ │ │ ├── foreach@2.0.5
│ │ │ │ │ │ ├── isarray@0.0.1
│ │ │ │ │ │ └── object-keys@1.0.11
│ │ │ │ │ ├─┬ has@1.0.1
│ │ │ │ │ │ └── function-bind@1.1.0
│ │ │ │ │ ├── object-inspect@0.4.0
│ │ │ │ │ ├─┬ quote-stream@0.0.0
│ │ │ │ │ │ └── minimist@0.0.8
│ │ │ │ │ ├─┬ readable-stream@1.0.34
│ │ │ │ │ │ └── isarray@0.0.1
│ │ │ │ │ ├── shallow-copy@0.0.1
│ │ │ │ │ ├─┬ static-eval@0.2.4
│ │ │ │ │ │ └─┬ escodegen@0.0.28
│ │ │ │ │ │   ├── esprima@1.0.4
│ │ │ │ │ │   └── estraverse@1.3.2
│ │ │ │ │ └─┬ through2@0.4.2
│ │ │ │ │   └─┬ xtend@2.1.2
│ │ │ │ │     └── object-keys@0.4.0
│ │ │ │ └── through2@2.0.1
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ ├── protocol-buffers-schema@2.2.0
│ │ │ └─┬ signed-varint@2.0.0
│ │ │   └── varint@3.0.1
│ │ ├── pull-stream@3.4.5
│ │ ├── pull-traverse@1.0.3
│ │ └── stable@0.1.5
│ ├── is-ipfs@0.2.1
│ ├── isstream@0.1.2
│ ├─┬ multiaddr@2.0.3
│ │ ├── ip@1.1.3
│ │ ├── lodash.filter@4.6.0
│ │ ├── lodash.map@4.6.0
│ │ ├── varint@4.0.1
│ │ └── xtend@4.0.1
│ ├─┬ multipart-stream@2.0.1
│ │ ├── is-stream@1.1.0
│ │ └── sandwich-stream@1.0.0
│ ├─┬ ndjson@1.4.3
│ │ ├── minimist@1.2.0
│ │ ├─┬ split2@0.2.1
│ │ │ └─┬ through2@0.6.5
│ │ │   └─┬ readable-stream@1.0.34
│ │ │     └── isarray@0.0.1
│ │ └─┬ through2@0.6.5
│ │   └─┬ readable-stream@1.0.34
│ │     └── isarray@0.0.1
│ ├─┬ peer-id@0.7.0
│ │ └─┬ libp2p-crypto@0.5.0
│ │   ├─┬ elliptic@6.3.2
│ │   │ ├── bn.js@4.11.6
│ │   │ ├── brorand@1.0.6
│ │   │ └── hash.js@1.0.3
│ │   └── node-forge@0.6.43
│ ├── peer-info@0.7.1
│ ├── promisify-es6@1.0.2
│ ├── qs@6.2.1
│ ├── streamifier@0.1.1
│ ├─┬ tar-stream@1.5.2
│ │ └─┬ end-of-stream@1.1.0
│ │   └── once@1.3.3
│ └─┬ wreck@10.0.0
│   ├── boom@4.1.0
│   └── hoek@4.1.0
├─┬ ipfs-daemon@0.0.2
│ ├─┬ go-ipfs-dep@0.4.4-floodsub2  (git+https://github.com/haadcode/go-ipfs-dep.git#9f162e014b0ff50ff81df50715b98dad7c60b870)
│ │ ├── go-platform@1.0.0
│ │ ├─┬ gunzip-maybe@1.3.1
│ │ │ ├─┬ browserify-zlib@0.1.4
│ │ │ │ └── pako@0.2.9
│ │ │ ├── is-deflate@1.0.0
│ │ │ ├── is-gzip@1.0.0
│ │ │ ├─┬ peek-stream@1.1.1
│ │ │ │ ├─┬ duplexify@3.4.5
│ │ │ │ │ ├─┬ end-of-stream@1.0.0
│ │ │ │ │ │ └── once@1.3.3
│ │ │ │ │ └── stream-shift@1.0.0
│ │ │ │ └─┬ through2@0.5.1
│ │ │ │   ├─┬ readable-stream@1.0.34
│ │ │ │   │ └── isarray@0.0.1
│ │ │ │   └── xtend@3.0.0
│ │ │ ├── pumpify@1.3.5
│ │ │ └─┬ through2@0.4.2
│ │ │   ├─┬ readable-stream@1.0.34
│ │ │   │ └── isarray@0.0.1
│ │ │   └─┬ xtend@2.1.2
│ │ │     └── object-keys@0.4.0
│ │ ├─┬ request@2.75.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.4.1
│ │ │ ├── caseless@0.11.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.0
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@2.0.0
│ │ │ │ └── asynckit@0.4.0
│ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ ├─┬ chalk@1.1.3
│ │ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ ├─┬ commander@2.9.0
│ │ │ │ │ └── graceful-readlink@1.0.1
│ │ │ │ ├─┬ is-my-json-valid@2.15.0
│ │ │ │ │ └── jsonpointer@4.0.0
│ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │   └── pinkie@2.0.4
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├── boom@2.10.1
│ │ │ │ ├─┬ cryptiles@2.0.5
│ │ │ │ │ └─┬ boom@2.10.1
│ │ │ │ │   └── hoek@2.16.3
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └─┬ sntp@1.0.9
│ │ │ │   └── hoek@2.16.3
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.3.1
│ │ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └── verror@1.3.6
│ │ │ │ └─┬ sshpk@1.10.1
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├── bcrypt-pbkdf@1.0.0
│ │ │ │   ├─┬ dashdash@1.14.0
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── ecc-jsbn@0.1.1
│ │ │ │   ├─┬ getpass@0.1.6
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── jodid25519@1.0.2
│ │ │ │   ├── jsbn@0.1.0
│ │ │ │   └── tweetnacl@0.14.3
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.12
│ │ │ │ └── mime-db@1.24.0
│ │ │ ├── node-uuid@1.4.7
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── stringstream@0.0.5
│ │ │ ├── tough-cookie@2.3.1
│ │ │ └── tunnel-agent@0.4.3
│ │ └─┬ tar-fs@1.13.2
│ │   ├─┬ mkdirp@0.5.1
│ │   │ └── minimist@0.0.8
│ │   └── pump@1.0.1
│ ├─┬ ipfs-api@8.1.0  (git+https://github.com/haadcode/js-ipfs-api.git#7e7f6eac63d037870096994a414b259a1ce2061a)
│ │ ├── ipfs-merkle-dag@0.7.3  (git+https://github.com/haadcode/js-ipfs-merkle-dag.git#2a31c2cb8bbba63f5269d5e24123c87a0284aaef)
│ │ └── js-base64@2.1.9
│ ├─┬ ipfsd-ctl@0.15.0  (git+https://github.com/haadcode/js-ipfsd-ctl.git#2747365c4c7e79610de3ff627073721b89952205)
│ │ ├─┬ ipfs-api@8.1.0  (git+https://github.com/haadcode/js-ipfs-api.git#7e7f6eac63d037870096994a414b259a1ce2061a)
│ │ │ └── ipfs-merkle-dag@0.7.3  (git+https://github.com/haadcode/js-ipfs-merkle-dag.git#2a31c2cb8bbba63f5269d5e24123c87a0284aaef)
│ │ ├── rimraf@2.5.4
│ │ ├── run-series@1.1.4
│ │ ├─┬ shutdown@0.2.4
│ │ │ ├── async@0.9.2
│ │ │ └─┬ debug@1.0.4
│ │ │   └── ms@0.6.2
│ │ └─┬ subcomandante@1.0.5
│ │   ├─┬ comandante@0.0.1
│ │   │ └── duplexer@0.0.4
│ │   ├── duplexer@0.1.1
│ │   └── is-running@1.0.5
│ └── logplease@1.2.7
└─┬ orbit-db@0.1.1
  ├─┬ asyncawait@1.0.6
  │ ├── fibers@1.0.15
  │ └── lodash@3.10.1
  ├── bluebird@3.4.6
  ├─┬ ipfsd-ctl@0.7.1
  │ ├── async@1.5.2
  │ ├─┬ go-ipfs@0.3.10
  │ │ ├─┬ extract-zip@1.5.0
  │ │ │ ├─┬ concat-stream@1.5.0
  │ │ │ │ └── typedarray@0.0.6
  │ │ │ ├── debug@0.7.4
  │ │ │ ├─┬ mkdirp@0.5.0
  │ │ │ │ └── minimist@0.0.8
  │ │ │ └─┬ yauzl@2.4.1
  │ │ │   └─┬ fd-slicer@1.0.1
  │ │ │     └── pend@1.2.0
  │ │ └─┬ nugget@1.6.2
  │ │   ├─┬ debug@2.2.0
  │ │   │ └── ms@0.7.1
  │ │   ├─┬ pretty-bytes@1.0.4
  │ │   │ ├── get-stdin@4.0.1
  │ │   │ └─┬ meow@3.7.0
  │ │   │   ├─┬ camelcase-keys@2.1.0
  │ │   │   │ └── camelcase@2.1.1
  │ │   │   ├── decamelize@1.2.0
  │ │   │   ├─┬ loud-rejection@1.6.0
  │ │   │   │ ├─┬ currently-unhandled@0.4.1
  │ │   │   │ │ └── array-find-index@1.0.2
  │ │   │   │ └── signal-exit@3.0.1
  │ │   │   ├── map-obj@1.0.1
  │ │   │   ├─┬ normalize-package-data@2.3.5
  │ │   │   │ ├── hosted-git-info@2.1.5
  │ │   │   │ ├─┬ is-builtin-module@1.0.0
  │ │   │   │ │ └── builtin-modules@1.1.1
  │ │   │   │ ├── semver@5.3.0
  │ │   │   │ └─┬ validate-npm-package-license@3.0.1
  │ │   │   │   ├─┬ spdx-correct@1.0.2
  │ │   │   │   │ └── spdx-license-ids@1.2.2
  │ │   │   │   └── spdx-expression-parse@1.0.4
  │ │   │   ├─┬ read-pkg-up@1.0.1
  │ │   │   │ ├─┬ find-up@1.1.2
  │ │   │   │ │ └── path-exists@2.1.0
  │ │   │   │ └─┬ read-pkg@1.1.0
  │ │   │   │   ├─┬ load-json-file@1.1.0
  │ │   │   │   │ ├─┬ parse-json@2.2.0
  │ │   │   │   │ │ └─┬ error-ex@1.3.0
  │ │   │   │   │ │   └── is-arrayish@0.2.1
  │ │   │   │   │ └── pify@2.3.0
  │ │   │   │   └── path-type@1.1.0
  │ │   │   ├─┬ redent@1.0.0
  │ │   │   │ ├─┬ indent-string@2.1.0
  │ │   │   │ │ └─┬ repeating@2.0.1
  │ │   │   │ │   └─┬ is-finite@1.0.2
  │ │   │   │ │     └── number-is-nan@1.0.1
  │ │   │   │ └── strip-indent@1.0.1
  │ │   │   └── trim-newlines@1.0.0
  │ │   ├─┬ progress-stream@1.2.0
  │ │   │ ├── speedometer@0.1.4
  │ │   │ └─┬ through2@0.2.3
  │ │   │   ├─┬ readable-stream@1.1.14
  │ │   │   │ └── isarray@0.0.1
  │ │   │   └─┬ xtend@2.1.2
  │ │   │     └── object-keys@0.4.0
  │ │   ├── single-line-log@0.4.1
  │ │   └── throttleit@0.0.2
  │ ├─┬ ipfs-api@2.13.2
  │ │ ├── merge-stream@1.0.0
  │ │ ├── require-dir@0.3.1
  │ │ ├─┬ vinyl@1.2.0
  │ │ │ ├── clone@1.0.2
  │ │ │ ├── clone-stats@0.0.1
  │ │ │ └── replace-ext@0.0.1
  │ │ ├─┬ vinyl-fs-browser@2.1.1-1
  │ │ │ ├─┬ glob-stream@5.3.5
  │ │ │ │ ├── glob@5.0.15
  │ │ │ │ ├─┬ glob-parent@3.0.0
  │ │ │ │ │ └─┬ is-glob@3.0.0
  │ │ │ │ │   └── is-extglob@2.0.0
  │ │ │ │ ├─┬ micromatch@2.3.11
  │ │ │ │ │ ├─┬ arr-diff@2.0.0
  │ │ │ │ │ │ └── arr-flatten@1.0.1
  │ │ │ │ │ ├── array-unique@0.2.1
  │ │ │ │ │ ├─┬ braces@1.8.5
  │ │ │ │ │ │ ├─┬ expand-range@1.8.2
  │ │ │ │ │ │ │ └─┬ fill-range@2.2.3
  │ │ │ │ │ │ │   ├── is-number@2.1.0
  │ │ │ │ │ │ │   ├── isobject@2.1.0
  │ │ │ │ │ │ │   ├── randomatic@1.1.5
  │ │ │ │ │ │ │   └── repeat-string@1.5.4
  │ │ │ │ │ │ ├── preserve@0.2.0
  │ │ │ │ │ │ └── repeat-element@1.1.2
  │ │ │ │ │ ├─┬ expand-brackets@0.1.5
  │ │ │ │ │ │ └── is-posix-bracket@0.1.1
  │ │ │ │ │ ├─┬ extglob@0.3.2
  │ │ │ │ │ │ └── is-extglob@1.0.0
  │ │ │ │ │ ├── filename-regex@2.0.0
  │ │ │ │ │ ├── is-extglob@1.0.0
  │ │ │ │ │ ├── is-glob@2.0.1
  │ │ │ │ │ ├─┬ kind-of@3.0.4
  │ │ │ │ │ │ └── is-buffer@1.1.4
  │ │ │ │ │ ├── normalize-path@2.0.1
  │ │ │ │ │ ├─┬ object.omit@2.0.0
  │ │ │ │ │ │ ├─┬ for-own@0.1.4
  │ │ │ │ │ │ │ └── for-in@0.1.6
  │ │ │ │ │ │ └── is-extendable@0.1.1
  │ │ │ │ │ ├─┬ parse-glob@3.0.4
  │ │ │ │ │ │ ├─┬ glob-base@0.3.0
  │ │ │ │ │ │ │ ├── glob-parent@2.0.0
  │ │ │ │ │ │ │ └─┬ is-glob@2.0.1
  │ │ │ │ │ │ │   └── is-extglob@1.0.0
  │ │ │ │ │ │ ├── is-dotfile@1.0.2
  │ │ │ │ │ │ ├── is-extglob@1.0.0
  │ │ │ │ │ │ └── is-glob@2.0.1
  │ │ │ │ │ └─┬ regex-cache@0.4.3
  │ │ │ │ │   ├── is-equal-shallow@0.1.3
  │ │ │ │ │   └── is-primitive@2.0.0
  │ │ │ │ ├── ordered-read-streams@0.3.0
  │ │ │ │ ├─┬ through2@0.6.5
  │ │ │ │ │ └─┬ readable-stream@1.0.34
  │ │ │ │ │   └── isarray@0.0.1
  │ │ │ │ ├─┬ to-absolute-glob@0.1.1
  │ │ │ │ │ └── extend-shallow@2.0.1
  │ │ │ │ └─┬ unique-stream@2.2.1
  │ │ │ │   └─┬ json-stable-stringify@1.0.1
  │ │ │ │     └── jsonify@0.0.0
  │ │ │ ├── graceful-fs@4.1.9
  │ │ │ ├─┬ gulp-sourcemaps@1.7.1
  │ │ │ │ ├── acorn@4.0.3
  │ │ │ │ ├── convert-source-map@1.3.0
  │ │ │ │ ├─┬ css@2.2.1
  │ │ │ │ │ ├─┬ source-map-resolve@0.3.1
  │ │ │ │ │ │ ├── atob@1.1.3
  │ │ │ │ │ │ ├── resolve-url@0.2.1
  │ │ │ │ │ │ └── source-map-url@0.3.0
  │ │ │ │ │ └── urix@0.1.0
  │ │ │ │ ├── detect-newline@2.1.0
  │ │ │ │ └─┬ source-map@0.1.43
  │ │ │ │   └── amdefine@1.0.0
  │ │ │ ├── is-valid-glob@0.3.0
  │ │ │ ├── object-assign@4.1.0
  │ │ │ ├─┬ strip-bom@2.0.0
  │ │ │ │ └── is-utf8@0.2.1
  │ │ │ ├─┬ strip-bom-stream@1.0.0
  │ │ │ │ └── first-chunk-stream@1.0.0
  │ │ │ └── through2-filter@2.0.0
  │ │ ├─┬ vinyl-multipart-stream@1.2.6
  │ │ │ └─┬ vinyl-fs-that-respects-files@1.0.2
  │ │ │   ├─┬ glob-watcher@2.0.0
  │ │ │   │ └─┬ gaze@0.5.2
  │ │ │   │   └─┬ globule@0.1.0
  │ │ │   │     ├─┬ glob@3.1.21
  │ │ │   │     │ ├── graceful-fs@1.2.3
  │ │ │   │     │ └── inherits@1.0.2
  │ │ │   │     ├── lodash@1.0.2
  │ │ │   │     └─┬ minimatch@0.2.14
  │ │ │   │       ├── lru-cache@2.7.3
  │ │ │   │       └── sigmund@1.0.1
  │ │ │   ├─┬ merge-stream@0.1.8
  │ │ │   │ └─┬ through2@0.6.5
  │ │ │   │   └─┬ readable-stream@1.0.34
  │ │ │   │     └── isarray@0.0.1
  │ │ │   ├── object-assign@3.0.0
  │ │ │   └── vinyl@0.5.3
  │ │ └─┬ wreck@7.2.1
  │ │   └── boom@3.2.2
  │ └── multiaddr@1.4.1
  ├─┬ redis@2.6.2
  │ ├── double-ended-queue@2.1.0-0
  │ ├── redis-commands@1.2.0
  │ └── redis-parser@2.0.4
  ├─┬ sqlite3@3.1.6
  │ ├── nan@2.3.5
  │ └─┬ node-pre-gyp@0.6.30
  │   ├─┬ mkdirp@0.5.1
  │   │ └── minimist@0.0.8
  │   ├─┬ nopt@3.0.6
  │   │ └── abbrev@1.0.9
  │   ├─┬ npmlog@4.0.0
  │   │ ├─┬ are-we-there-yet@1.1.2
  │   │ │ ├── delegates@1.0.0
  │   │ │ └─┬ readable-stream@2.1.5
  │   │ │   ├── buffer-shims@1.0.0
  │   │ │   ├── core-util-is@1.0.2
  │   │ │   ├── inherits@2.0.3
  │   │ │   ├── isarray@1.0.0
  │   │ │   ├── process-nextick-args@1.0.7
  │   │ │   ├── string_decoder@0.10.31
  │   │ │   └── util-deprecate@1.0.2
  │   │ ├── console-control-strings@1.1.0
  │   │ ├─┬ gauge@2.6.0
  │   │ │ ├── aproba@1.0.4
  │   │ │ ├── has-color@0.1.7
  │   │ │ ├── has-unicode@2.0.1
  │   │ │ ├── object-assign@4.1.0
  │   │ │ ├── signal-exit@3.0.1
  │   │ │ ├─┬ string-width@1.0.2
  │   │ │ │ ├─┬ code-point-at@1.0.1
  │   │ │ │ │ └── number-is-nan@1.0.1
  │   │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │   │ │ │   └── number-is-nan@1.0.1
  │   │ │ ├─┬ strip-ansi@3.0.1
  │   │ │ │ └── ansi-regex@2.0.0
  │   │ │ └── wide-align@1.1.0
  │   │ └── set-blocking@2.0.0
  │   ├─┬ rc@1.1.6
  │   │ ├── deep-extend@0.4.1
  │   │ ├── ini@1.3.4
  │   │ ├── minimist@1.2.0
  │   │ └── strip-json-comments@1.0.4
  │   ├─┬ request@2.75.0
  │   │ ├── aws-sign2@0.6.0
  │   │ ├── aws4@1.4.1
  │   │ ├─┬ bl@1.1.2
  │   │ │ └─┬ readable-stream@2.0.6
  │   │ │   ├── core-util-is@1.0.2
  │   │ │   ├── inherits@2.0.3
  │   │ │   ├── isarray@1.0.0
  │   │ │   ├── process-nextick-args@1.0.7
  │   │ │   ├── string_decoder@0.10.31
  │   │ │   └── util-deprecate@1.0.2
  │   │ ├── caseless@0.11.0
  │   │ ├─┬ combined-stream@1.0.5
  │   │ │ └── delayed-stream@1.0.0
  │   │ ├── extend@3.0.0
  │   │ ├── forever-agent@0.6.1
  │   │ ├─┬ form-data@2.0.0
  │   │ │ └── asynckit@0.4.0
  │   │ ├─┬ har-validator@2.0.6
  │   │ │ ├─┬ chalk@1.1.3
  │   │ │ │ ├── ansi-styles@2.2.1
  │   │ │ │ ├── escape-string-regexp@1.0.5
  │   │ │ │ ├─┬ has-ansi@2.0.0
  │   │ │ │ │ └── ansi-regex@2.0.0
  │   │ │ │ ├─┬ strip-ansi@3.0.1
  │   │ │ │ │ └── ansi-regex@2.0.0
  │   │ │ │ └── supports-color@2.0.0
  │   │ │ ├─┬ commander@2.9.0
  │   │ │ │ └── graceful-readlink@1.0.1
  │   │ │ ├─┬ is-my-json-valid@2.15.0
  │   │ │ │ ├── generate-function@2.0.0
  │   │ │ │ ├─┬ generate-object-property@1.2.0
  │   │ │ │ │ └── is-property@1.0.2
  │   │ │ │ ├── jsonpointer@4.0.0
  │   │ │ │ └── xtend@4.0.1
  │   │ │ └─┬ pinkie-promise@2.0.1
  │   │ │   └── pinkie@2.0.4
  │   │ ├─┬ hawk@3.1.3
  │   │ │ ├── boom@2.10.1
  │   │ │ ├── cryptiles@2.0.5
  │   │ │ ├── hoek@2.16.3
  │   │ │ └── sntp@1.0.9
  │   │ ├─┬ http-signature@1.1.1
  │   │ │ ├── assert-plus@0.2.0
  │   │ │ ├─┬ jsprim@1.3.1
  │   │ │ │ ├── extsprintf@1.0.2
  │   │ │ │ ├── json-schema@0.2.3
  │   │ │ │ └── verror@1.3.6
  │   │ │ └─┬ sshpk@1.10.1
  │   │ │   ├── asn1@0.2.3
  │   │ │   ├── assert-plus@1.0.0
  │   │ │   ├── bcrypt-pbkdf@1.0.0
  │   │ │   ├── dashdash@1.14.0
  │   │ │   ├── ecc-jsbn@0.1.1
  │   │ │   ├── getpass@0.1.6
  │   │ │   ├── jodid25519@1.0.2
  │   │ │   ├── jsbn@0.1.0
  │   │ │   └── tweetnacl@0.14.3
  │   │ ├── is-typedarray@1.0.0
  │   │ ├── isstream@0.1.2
  │   │ ├── json-stringify-safe@5.0.1
  │   │ ├─┬ mime-types@2.1.12
  │   │ │ └── mime-db@1.24.0
  │   │ ├── node-uuid@1.4.7
  │   │ ├── oauth-sign@0.8.2
  │   │ ├── qs@6.2.1
  │   │ ├── stringstream@0.0.5
  │   │ ├── tough-cookie@2.3.1
  │   │ └── tunnel-agent@0.4.3
  │   ├─┬ rimraf@2.5.4
  │   │ └─┬ glob@7.1.0
  │   │   ├── fs.realpath@1.0.0
  │   │   ├─┬ inflight@1.0.5
  │   │   │ └── wrappy@1.0.2
  │   │   ├── inherits@2.0.3
  │   │   ├─┬ minimatch@3.0.3
  │   │   │ └─┬ brace-expansion@1.1.6
  │   │   │   ├── balanced-match@0.4.2
  │   │   │   └── concat-map@0.0.1
  │   │   ├─┬ once@1.4.0
  │   │   │ └── wrappy@1.0.2
  │   │   └── path-is-absolute@1.0.1
  │   ├── semver@5.3.0
  │   ├─┬ tar@2.2.1
  │   │ ├── block-stream@0.0.9
  │   │ ├─┬ fstream@1.0.10
  │   │ │ └── graceful-fs@4.1.9
  │   │ └── inherits@2.0.3
  │   └─┬ tar-pack@3.1.4
  │     ├─┬ debug@2.2.0
  │     │ └── ms@0.7.1
  │     ├─┬ fstream@1.0.10
  │     │ ├── graceful-fs@4.1.9
  │     │ └── inherits@2.0.3
  │     ├─┬ fstream-ignore@1.0.5
  │     │ ├── inherits@2.0.3
  │     │ └─┬ minimatch@3.0.3
  │     │   └─┬ brace-expansion@1.1.6
  │     │     ├── balanced-match@0.4.2
  │     │     └── concat-map@0.0.1
  │     ├─┬ once@1.3.3
  │     │ └── wrappy@1.0.2
  │     ├─┬ readable-stream@2.1.5
  │     │ ├── buffer-shims@1.0.0
  │     │ ├── core-util-is@1.0.2
  │     │ ├── inherits@2.0.3
  │     │ ├── isarray@1.0.0
  │     │ ├── process-nextick-args@1.0.7
  │     │ ├── string_decoder@0.10.31
  │     │ └── util-deprecate@1.0.2
  │     └── uid-number@0.0.6
  └─┬ unirest@0.4.2
    ├─┬ form-data@0.2.0
    │ ├── async@0.9.2
    │ ├─┬ combined-stream@0.0.7
    │ │ └── delayed-stream@0.0.5
    │ └─┬ mime-types@2.0.14
    │   └── mime-db@1.12.0
    ├── mime@1.2.11
    └─┬ request@2.51.0
      ├── aws-sign2@0.5.0
      ├─┬ bl@0.9.5
      │ └─┬ readable-stream@1.0.34
      │   └── isarray@0.0.1
      ├── caseless@0.8.0
      ├── forever-agent@0.5.2
      ├─┬ hawk@1.1.1
      │ ├── boom@0.4.2
      │ ├── cryptiles@0.2.2
      │ ├── hoek@0.9.1
      │ └── sntp@0.2.4
      ├─┬ http-signature@0.10.1
      │ ├── asn1@0.1.11
      │ ├── assert-plus@0.1.5
      │ └── ctype@0.5.3
      ├── mime-types@1.0.2
      ├── oauth-sign@0.5.0
      └── qs@2.3.3
```

**Comment by haadcode** [comment]
I think this is due an old version of orbit-db:
`└─┬ orbit-db@0.1.1`

In your [package.json](https://github.com/brainstorm/cgt-orbitsearch/blob/master/package.json#L18), you should define the version as `^0.13.1`, so:
`"orbit-db": "^0.13.1",`

That should work (I hope). Let me know if this fixes it.

**Comment by brainstorm** [comment]
Thanks @haadcode. I just started over (rm -rf `node_modules`), pinned the versions as you suggested and here's how npm looks like:

```
mba:cgt-vcfsearch romanvg$ npm list | grep orbit
└─┬ orbit-db@0.13.1
  ├─┬ orbit-db-counterstore@0.1.4
  │ └─┬ orbit-db-store@0.1.6
  ├─┬ orbit-db-docstore@0.0.7
  │ └── orbit-db-store@0.1.3
  ├─┬ orbit-db-eventstore@0.1.5
  ├── orbit-db-feedstore@0.1.4
  ├── orbit-db-kvstore@0.1.3
  └── orbit-db-pubsub@0.0.5
```

But the `node orbit_t.js` test (copy & pasted from the README.md) still fails:

```
mba:cgt-vcfsearch romanvg$ node orbit_t.js
/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:14
      this._ipfs.pubsub.sub(hash, { discover: true }, (err, stream) => {
                       ^

TypeError: Cannot read property 'sub' of undefined
    at IPFSPubsub.subscribe (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:14:24)
    at OrbitDB._subscribe (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/OrbitDB.js:71:20)
    at OrbitDB._createStore (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/OrbitDB.js:62:17)
    at OrbitDB.eventlog (/Users/romanvg/dev/cgt-vcfsearch/node_modules/orbit-db/src/OrbitDB.js:30:17)
    at Object.<anonymous> (/Users/romanvg/dev/cgt-vcfsearch/orbit_t.js:7:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by haadcode** [comment]
Ok. Really sorry for the troubles. This is something we need to fix in a way that you don't have to go through all these hoops :/

So, it seems you need to install a custom version of `ipfs-api`, specifically `https://github.com/haadcode/js-ipfs-api.git`, so change the dep in package.json for ipfs-api to `https://github.com/haadcode/js-ipfs-api.git` (I'll fix the readme for orbit-db to reflect this).

Also, ran your code and found another problem with orbit-db and fixed it, so please use 0.13.2 now for orbit-db:
```json
  "dependencies": {
    "ipfs-api": "https://github.com/haadcode/js-ipfs-api.git",
    "ipfs-daemon": "^0.0.3",
    "orbit-db": "^0.13.2",
    "bionode-vcf": "^1.1.4"
  }
```

I hope this fixes it. Also, note that you need to run a local IPFS daemon version floodsub-2: https://dist.ipfs.io/go-ipfs/floodsub-2.

Let me know if you got it working.

**Comment by brainstorm** [comment]
Thanks much for following this up! That apparently made it yet I guess I've to install that specific `go-ipfs` now to be able to pubsub?:

```
$ node orbit_t.js
(node:81380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: experimental pubsub feature not enabled. Run daemon with --enable-pubsub-experiment to use.
[object Object]
(node:81380) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: experimental pubsub feature not enabled. Run daemon with --enable-pubsub-experiment to use.
```

**Comment by haadcode** [comment]
@brainstorm correct. You need to download https://dist.ipfs.io/go-ipfs/floodsub-2, run it like you would run an IPFS daemon (`ipfs daemon`) and that'll do it. 

Another option is to use https://github.com/haadcode/ipfs-daemon which comes with the correct version of IPFS.

**Comment by haadcode** [comment]
@brainstorm did this fix your issue? Is there anything else preventing you to proceed?

**Comment by brainstorm** [comment]
Yeah, thank you @haadcode for following this up and helping out, closing 👍
